### ISSUE TITLE
Initialize board with players' pieces

### ISSUE THREAD

**Issue by Wolfyre243** [Wolfyre243/Chess-Game#2]
# Summary
Using the `Board()` constructor, together with the `Player()` and `Pieces()` classes, we can initialize and print the starting board to the terminal.

## To-do
- [x] Generate pieces for the player with the `createPieces()` method in the `Player` class, giving each piece their allocated starting positions.
- [x] Add the pieces into a `List` in the `Player` class, which will store the player's `Pieces` data.
- [x] Load the player's `Pieces` into the 2D `spots` matrix that contains instances of the `Spot` class.
- [x] Print the `Board` in the `main` method; check if everything is placed correctly.

## Expected output:
{'♜ ','♞ ','♝ ','♛ ','♚ ','♝ ','♞ ','♜ '},
{'♟','♟','♟','♟','♟','♟','♟','♟',},
{'    ','    ','    ','    ','    ','    ','    ','    ','    ',},
{'    ','    ','    ','    ','    ','    ','    ','    ','    ',},
{'    ','    ','    ','    ','    ','    ','    ','    ','    ',},
{'    ','    ','    ','    ','    ','    ','    ','    ','    ',},
{' ♙',' ♙',' ♙',' ♙',' ♙',' ♙',' ♙',' ♙',},
{' ♖',' ♘',' ♗',' ♕',' ♔',' ♗',' ♘',' ♖'}

(ignore the pawns)

**Comment by Wolfyre243** [comment]
will need to add a new method to `Game` class for printing the board

**Comment by Wolfyre243** [comment]
its done
