### ISSUE TITLE
Implement user input system (Testing)

### ISSUE THREAD

**Issue by Wolfyre243** [Wolfyre243/Chess-Game#3]
# Summary
Add user input to the game, using `System.in`. This excludes gameplay as that will be a separate issue to resolve later on (its much more complicated)

## To-do
- [x] In the `Game` class, add a `Scanner` class to receive user input in the `main` method.
- [x] Using a `while` loop, along with logic statements, parse the user input through an external method in the `Game` class./
- [x] Print the parsed user input to check code.

## Expected output:
Moving knight to e4
or
Invalid input!

**Comment by Wolfyre243** [comment]
IT WORKS OMG
