### ISSUE TITLE
Check and save moves made by player

### ISSUE THREAD

**Issue by Wolfyre243** [Wolfyre243/Chess-Game#4]
# Summary
Create a `Move` class to hold move data. Update the individual chess piece classes with a method to check a move's validity.

## To-do
- [x] Create a class `Move`
- [ ] Add crucial fields in `Move` such as `pieceToMove`, current `x` `y` values of the piece and the destination.
- [ ] Add a method `isValid()` to each individual chess piece class to check the validity of a move.
- [ ] Save the move message sent in `executeMove()` into `move`, for the sake of move logging
