### ISSUE TITLE
Implement the start game system

### ISSUE THREAD

**Issue by Wolfyre243** [Wolfyre243/Chess-Game#6]
# Summary
Do a bit of rearranging to facilitate smoother and efficient logic during the game, and add a few print statements when a game starts

## To-do
- [x] Add a method called `enterPlayer()` in the `Game` class, which should assign a player instance to the `Game` classes' player fields (p1 and p2).
- [x] Add name fields for `Player` class.
- [x] Create a new `Game` instance when a game begins. This should also create a new `Board`.
- [x] Add the text for the start of a turn, and print the current board. (Ignore making moves for now)
